spring:
  application:
    name: ${SPRING_APP_NAME:SchoolManagementSystem}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/school_system
    username: root
    password: password

    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
  data:
    jdbc:
      dialect: mysql
#  security:
#    user:
#      name: ${SECURITY_USERNAME:ziad}
#      password: ${SECURITY_PASSWORD:12345}
  config:
    import: classpath:application_production.yml
  profiles:
    default: default
server:
  port: 1234
springdoc:
  swagger-ui:
    path: /swagger-ui.html

#  main:
#    allow-circular-references: true
#  cache:
#    redis:
#      cache-null-values: true
#    type: redis
logging:
  level:
    org.springframework.security: debug
#    sql: debug
#    root: debug
security.jwt.secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  # 1h in millisecond
security.jwt.expiration-time: 3600000